In [1]:
import pandas as pd

# Load dataset
df = pd.read_excel(r"C:\Users\Tushar\Downloads\Projects\Sales Performance & Profitability Analysis\Data\Raw Data\Sales_Dataset_Raw.xlsx")

# Preview data
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Location,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1.0,CA-2016-152156,NaT,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,"United States,Henderson",Kentucky,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2.0,CA-2016-152156,NaT,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,"United States,Henderson",Kentucky,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3.0,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,"United States,Los Angeles",California,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4.0,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,"United States,Fort Lauderdale",Florida,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5.0,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,"United States,Fort Lauderdale",Florida,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [3]:
df.shape

(10164, 20)

In [4]:
df.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Location', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit'],
      dtype='object')

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10164 entries, 0 to 10163
Data columns (total 20 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9658 non-null   float64
 1   Order ID       9657 non-null   object
 2   Order Date     9655 non-null   datetime64[ns]
 3   Ship Date      10164 non-null  datetime64[ns]
 4   Ship Mode      10164 non-null  object
 5   Customer ID    10164 non-null  object
 6   Customer Name  10164 non-null  object
 7   Segment        10164 non-null  object
 8   Location       10164 non-null  object
 9   State          10164 non-null  object
 10  Postal Code    10164 non-null  int64
 11  Region         10164 non-null  object
 12  Product ID     10164 non-null  object
 13  Category       10164 non-null  object
 14  Sub-Category   10164 non-null  object
 15  Product Name   10164 non-null  object
 16  Sales          10164 non-null  float64
 17  Quantity       10164 non-null  int64
 18  Discount       10164 non-null  float64
 19  Profit         10164 non-null  float64
dtypes: datetime64[ns](2), float64(4), int64(2), object(12)
memory usage: 1.6+ MB

In [6]:
df.describe()

,Row ID,Order Date,Ship Date,Postal Code,Sales,Quantity,Discount,Profit
count,9658.000000,9655,10164,10164.000000,10164.000000,10164.000000,10164.000000,10164.000000
mean,5465.057776,2016-04-29 14:26:05.282237184,2016-05-03 21:38:36.410861824,59671.840319,1363.224294,4.454054,0.194482,449.515052
min,1.000000,2014-01-04 00:00:00,2014-01-07 00:00:00,1040.000000,0.444000,1.000000,0.000000,-6599.978000
25%,2519.250000,2015-05-23 00:00:00,2015-05-26 00:00:00,23320.000000,17.472000,2.000000,0.000000,1.790100
50%,5039.500000,2016-06-26 00:00:00,2016-06-29 00:00:00,60076.000000,55.988000,3.000000,0.200000,8.796750
75%,7571.750000,2017-05-14 00:00:00,2017-05-18 00:00:00,90008.000000,220.716000,5.000000,0.200000,30.585600
max,49970.000000,2017-12-30 00:00:00,2018-01-05 00:00:00,496505.000000,113192.400000,70.000000,4.000000,41999.880000
std,5420.122695,NaN,NaN,54314.040291,11276.870636,6.960675,0.434531,4190.075702

In [7]:
df.isnull().sum()

Row ID           506
Order ID         507
Order Date       509
Ship Date          0
Ship Mode          0
Customer ID        0
Customer Name      0
Segment            0
Location           0
State              0
Postal Code        0
Region             0
Product ID         0
Category           0
Sub-Category       0
Product Name       0
Sales              0
Quantity           0
Discount           0
Profit             0
dtype: int64

In [8]:
df.duplicated().sum()

122

In [9]:
# Check current data types
df.dtypes

Row ID                  float64
Order ID                 object
Order Date       datetime64[ns]
Ship Date        datetime64[ns]
Ship Mode                object
Customer ID              object
Customer Name            object
Segment                  object
Location                 object
State                    object
Postal Code               int64
Region                   object
Product ID               object
Category                 object
Sub-Category             object
Product Name             object
Sales                   float64
Quantity                  int64
Discount                float64
Profit                  float64
dtype: object

In [11]:
df["Quantity"] = pd.to_numeric(df["Quantity"], errors="coerce")

df["Quantity"].head()

0    2
1    3
2    2
3    5
4    2
Name: Quantity, dtype: int64